// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import ChangeLocationReducer from "../change_location_reducer";
import CreateCharacterReducer from "../create_character_reducer";
import DebugReducer from "../debug_reducer";

export type ChangeLocationParams = __Infer<typeof ChangeLocationReducer>;
export type CreateCharacterParams = __Infer<typeof CreateCharacterReducer>;
export type DebugParams = __Infer<typeof DebugReducer>;

