// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  SpawnLocation,
  Drink,
} from "./types";


export default __t.row({
  characterId: __t.i32().primaryKey().name("character_id"),
  playerId: __t.i32().name("player_id"),
  get location() {
    return SpawnLocation;
  },
  name: __t.string(),
  get drink() {
    return Drink;
  },
});
