// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Character = __t.object("Character", {
  characterId: __t.i32(),
  playerId: __t.i32(),
  get location() {
    return SpawnLocation;
  },
  name: __t.string(),
  get drink() {
    return Drink;
  },
});
export type Character = __Infer<typeof Character>;

export const Config = __t.object("Config", {
  id: __t.i32(),
  worldSize: __t.i64(),
});
export type Config = __Infer<typeof Config>;

export const Drink = __t.object("Drink", {
  get drinkBase() {
    return DrinkBase;
  },
  get milk() {
    return Milk;
  },
  get flavor() {
    return Flavor;
  },
  get temperature() {
    return Temperature;
  },
  get size() {
    return Size;
  },
});
export type Drink = __Infer<typeof Drink>;

// The tagged union or sum type for the algebraic type `DrinkBase`.
export const DrinkBase = __t.enum("DrinkBase", {
  Hojicha: __t.unit(),
  Matcha: __t.unit(),
});
export type DrinkBase = __Infer<typeof DrinkBase>;

// The tagged union or sum type for the algebraic type `Flavor`.
export const Flavor = __t.enum("Flavor", {
  Banana: __t.unit(),
  Rose: __t.unit(),
  Vanilla: __t.unit(),
  Uji: __t.unit(),
  Roasted: __t.unit(),
});
export type Flavor = __Infer<typeof Flavor>;

// The tagged union or sum type for the algebraic type `Milk`.
export const Milk = __t.enum("Milk", {
  Whole: __t.unit(),
  Oat: __t.unit(),
});
export type Milk = __Infer<typeof Milk>;

export const Player = __t.object("Player", {
  identity: __t.identity(),
  playerId: __t.i32(),
  name: __t.string(),
  activeCharacterId: __t.i32(),
});
export type Player = __Infer<typeof Player>;

// The tagged union or sum type for the algebraic type `Size`.
export const Size = __t.enum("Size", {
  Small: __t.unit(),
  Large: __t.unit(),
});
export type Size = __Infer<typeof Size>;

// The tagged union or sum type for the algebraic type `SpawnLocation`.
export const SpawnLocation = __t.enum("SpawnLocation", {
  None: __t.unit(),
  Room640: __t.unit(),
  MfaArea: __t.unit(),
});
export type SpawnLocation = __Infer<typeof SpawnLocation>;

// The tagged union or sum type for the algebraic type `Temperature`.
export const Temperature = __t.enum("Temperature", {
  Hot: __t.unit(),
  Iced: __t.unit(),
});
export type Temperature = __Infer<typeof Temperature>;

